# Generated by Django 3.2.25 on 2024-04-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=75)),
                ('fechaNacimiento', models.DateField()),
                ('pago', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
